<!-- SERVICES
================================================== -->
<section class="bg-light">
    <div class="container">
        <div class="section-title mb-1-9 mb-md-6 text-center wow fadeInUp" data-wow-delay="200ms">
            <span>Our product</span>
            <h2 class="mb-0 h1 mt-2">Our Company Solutions</h2>
        </div>
        <div class="row gx-xxl-5 mt-n1-9">
            <style>
                .card-style-01 {
                    position: relative;
                    overflow: hidden;
                    border-radius: 20px;
                    box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);
                    transition: transform 0.3s ease;
                    height: 100%;
                    min-height: 420px;
                    padding: 25px;
                }

                .card-style-01 img {
                    width: 100%;
                    height: 220px;
                    object-fit: cover;
                    border-radius: 12px;
                }

                .card-content {
                    margin-top: 20px;
                }

                .card-content h3 {
                    font-size: 1.3rem;
                }

                .card-content-hover {
                    position: absolute;
                    top: 0;
                    left: 0;
                    right: 0;
                    bottom: 0;
                    background-color: rgba(0, 0, 0, 0.85);
                    opacity: 0;
                    transition: opacity 0.4s ease;
                    padding: 30px;
                    display: flex;
                    flex-direction: column;
                    justify-content: center;
                    align-items: center;
                    text-align: center;
                }

                .card-style-01:hover .card-content-hover {
                    opacity: 1;
                }

                .card-content-hover h3 {
                    font-size: 1.5rem;
                }

                .card-content-hover p {
                    font-size: 1rem;
                }

                .card-background img {
                    display: none;
                }

                .content-inner i {
                    font-size: 2rem;
                }
            </style>

            <!-- Card 1 -->
            <div class="col-md-6 col-lg-4 mt-1-9 wow fadeInUp" data-wow-delay="200ms">
                <div class="card-style-01">
                    <img src="assets/img/product2/1.png" alt="ACDB">
                    <div class="card-content">
                        <div class="content-inner">
                            <h3 class="mb-0 h5"><a href="solar-solutions.html">ACDB (AC Distribution Box)</a></h3>
                            <i class="flaticon-042-solar-panel display-13 text-secondary lh-1"></i>
                        </div>
                    </div>
                    <div class="card-content-hover">
                        <div class="content-inner">
                            <i class="flaticon-042-solar-panel display-13 text-white mb-2 d-block"></i>
                            <h3 class="h4 mb-3"><a href="solar-solutions.html" class="text-white">ACDB (AC Distribution Box)</a></h3>
                            <p class="mb-0 text-white opacity9">Our ACDB units are designed to manage and protect the AC power generated by solar systems. Built with premium quality components, they ensure safe distribution and overload protection, safeguarding your entire system.</p>
                        </div>
                        <div class="card-background"><img src="assets/img/product2/1.png" alt="ACDB"></div>
                    </div>
                </div>
            </div>

            <!-- Card 2 -->
            <div class="col-md-6 col-lg-4 mt-1-9 wow fadeInUp" data-wow-delay="300ms">
                <div class="card-style-01">
                    <img src="assets/img/product2/2.png" alt="DCDB">
                    <div class="card-content">
                        <div class="content-inner">
                            <h3 class="mb-0 h5"><a href="wind-turbine.html">DCDB (DC Distribution Box)</a></h3>
                            <i class="flaticon-047-windmill display-13 text-secondary lh-1"></i>
                        </div>
                    </div>
                    <div class="card-content-hover">
                        <div class="content-inner">
                            <i class="flaticon-047-windmill display-13 text-white mb-2 d-block"></i>
                            <h3 class="h4 mb-3"><a href="wind-turbine.html" class="text-white">DCDB (DC Distribution Box)</a></h3>
                            <p class="mb-0 text-white opacity9">DCDB units are crucial for protecting DC circuits from overcurrent and short circuits. Our DCDB solutions are reliable and durable, ensuring maximum safety and performance for your solar installation.</p>
                        </div>
                        <div class="card-background"><img src="assets/img/product2/2.png" alt="DCDB"></div>
                    </div>
                </div>
            </div>

            <!-- Card 3 -->
            <div class="col-md-6 col-lg-4 mt-1-9 wow fadeInUp" data-wow-delay="400ms">
                <div class="card-style-01">
                    <img src="assets/img/product2/3.png" alt="Solar Cables">
                    <div class="card-content">
                        <div class="content-inner">
                            <h3 class="mb-0 h5"><a href="renewable-energy.html">Solar Cables</a></h3>
                            <i class="flaticon-010-ecology-2 display-13 text-secondary lh-1"></i>
                        </div>
                    </div>
                    <div class="card-content-hover">
                        <div class="content-inner">
                            <i class="flaticon-010-ecology-2 display-13 text-white mb-2 d-block"></i>
                            <h3 class="h4 mb-3"><a href="renewable-energy.html" class="text-white">Solar Cables</a></h3>
                            <p class="mb-0 text-white opacity9">Our range of solar cables is designed for efficient power transmission with minimal loss. Resistant to UV radiation and harsh weather conditions, these cables ensure durability and long-lasting performance.</p>
                        </div>
                        <div class="card-background"><img src="assets/img/product2/3.png" alt="Solar Cables"></div>
                    </div>
                </div>
            </div>

            <!-- Card 4 -->
            <div class="col-md-6 col-lg-4 mt-1-9 wow fadeInUp" data-wow-delay="200ms">
                <div class="card-style-01">
                    <img src="assets/img/product2/4.png" alt="Earthing Kit">
                    <div class="card-content">
                        <div class="content-inner">
                            <h3 class="mb-0 h5"><a href="energy-transition.html">Earthing Kit</a></h3>
                            <i class="flaticon-005-tower display-13 text-secondary lh-1"></i>
                        </div>
                    </div>
                    <div class="card-content-hover">
                        <div class="content-inner">
                            <i class="flaticon-005-tower display-13 text-white mb-2 d-block"></i>
                            <h3 class="h4 mb-3"><a href="energy-transition.html" class="text-white">Earthing Kit</a></h3>
                            <p class="mb-0 text-white opacity9">Proper grounding is vital for safety and performance. Our earthing kits provide robust and reliable grounding solutions, reducing the risk of electrical faults and ensuring system longevity.</p>
                        </div>
                        <div class="card-background"><img src="assets/img/product2/4.png" alt="Earthing Kit"></div>
                    </div>
                </div>
            </div>

            <!-- Card 5 -->
            <div class="col-md-6 col-lg-4 mt-1-9 wow fadeInUp" data-wow-delay="300ms">
                <div class="card-style-01">
                    <img src="assets/img/product2/5.png" alt="MC4 Connector">
                    <div class="card-content">
                        <div class="content-inner">
                            <h3 class="mb-0 h5"><a href="global-optimization.html">MC4 Connector</a></h3>
                            <i class="flaticon-026-global-warming display-13 text-secondary lh-1"></i>
                        </div>
                    </div>
                    <div class="card-content-hover">
                        <div class="content-inner">
                            <i class="flaticon-026-global-warming display-13 text-white mb-2 d-block"></i>
                            <h3 class="h4 mb-3"><a href="global-optimization.html" class="text-white">MC4 Connector</a></h3>
                            <p class="mb-0 text-white opacity9">MC4 connectors from Anjali Enterprises are designed for quick and secure connections between solar panels and inverters. They are weatherproof, corrosion-resistant, and highly durable, making them ideal for any solar setup.</p>
                        </div>
                        <div class="card-background"><img src="assets/img/product2/5.png" alt="MC4 Connector"></div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- end services -->
